import { CustomCheck, GenerateRequest, SelectedCheck } from '../types';

function renderCheck(c: SelectedCheck): string {
  const p = c.params;
  const col = `"${c.columnName}"`;

  switch (c.checkId) {
    case 'not_null':
      return `validator.expect_column_values_to_not_be_null(${col})`;
    case 'unique':
      return `validator.expect_column_values_to_be_unique(${col})`;
    case 'null_percent':
      return `validator.expect_column_values_to_not_be_null(${col}, mostly=${p['mostly']})`;
    case 'values_in_set': {
      const vals = p['values'].split(',').map(v => `"${v.trim()}"`).join(', ');
      return `validator.expect_column_values_to_be_in_set(${col}, value_set=[${vals}])`;
    }
    case 'values_not_in_set': {
      const vals = p['values'].split(',').map(v => `"${v.trim()}"`).join(', ');
      return `validator.expect_column_values_to_not_be_in_set(${col}, value_set=[${vals}])`;
    }
    case 'unique_proportion':
      return `validator.expect_column_proportion_of_unique_values_to_be_between(${col}, min_value=${p['min']}, max_value=${p['max']})`;
    case 'min_between':
      return `validator.expect_column_min_to_be_between(${col}, min_value=${p['min']}, max_value=${p['max']})`;
    case 'max_between':
      return `validator.expect_column_max_to_be_between(${col}, min_value=${p['min']}, max_value=${p['max']})`;
    case 'mean_between':
      return `validator.expect_column_mean_to_be_between(${col}, min_value=${p['min']}, max_value=${p['max']})`;
    case 'sum_between':
      return `validator.expect_column_sum_to_be_between(${col}, min_value=${p['min']}, max_value=${p['max']})`;
    case 'stdev_between':
      return `validator.expect_column_stdev_to_be_between(${col}, min_value=${p['min']}, max_value=${p['max']})`;
    case 'quantile_between':
      return `validator.expect_column_quantile_values_to_be_between(\n    ${col},\n    quantile_ranges={"quantiles": [${p['quantile']}], "value_ranges": [[${p['min']}, ${p['max']}]]}\n)`;
    case 'length_between':
      return `validator.expect_column_value_lengths_to_be_between(${col}, min_value=${p['min']}, max_value=${p['max']})`;
    case 'match_regex':
      return `validator.expect_column_values_to_match_regex(${col}, regex=r"${p['regex']}")`;
    case 'strftime_format':
      return `validator.expect_column_values_to_match_strftime_format(${col}, strftime_format="${p['format']}")`;
    case 'date_parseable':
      return `validator.expect_column_values_to_be_dateutil_parseable(${col})`;
    case 'date_between':
      return `validator.expect_column_values_to_be_between(${col}, min_value="${p['min']}", max_value="${p['max']}")`;
    default:
      return `# unknown check: ${c.checkId}`;
  }
}

function renderCustom(c: CustomCheck): string {
  return [
    `validator.expect_column_values_to_satisfy(`,
    `    column="${c.columnName}",`,
    `    condition_parser="pandas",`,
    `    row_condition="${c.expression}",`,
    `    meta={"name": "${c.name}"}`,
    `)`,
  ].join('\n');
}

export function generateGE(req: GenerateRequest): string {
  const { table, checks, customChecks } = req;

  const header = [
    `# Great Expectations — ${table.schema}.${table.table}`,
    `# Generated by DQ Test Builder`,
    ``,
    `import great_expectations as gx`,
    ``,
    `context = gx.get_context()`,
    `suite_name = "${table.table}_suite"`,
    `suite = context.add_or_update_expectation_suite(expectation_suite_name=suite_name)`,
    ``,
    `# Replace with your actual batch request`,
    `validator = context.get_validator(`,
    `    batch_request=batch_request,`,
    `    expectation_suite_name=suite_name`,
    `)`,
    ``,
  ].join('\n');

  const byColumn = new Map<string, SelectedCheck[]>();
  for (const c of checks) {
    if (!byColumn.has(c.columnName)) byColumn.set(c.columnName, []);
    byColumn.get(c.columnName)!.push(c);
  }

  const body: string[] = [];
  for (const [col, colChecks] of byColumn) {
    body.push(`# ${col}`);
    for (const c of colChecks) body.push(renderCheck(c));
    body.push('');
  }

  if (customChecks.length > 0) {
    body.push('# Custom checks');
    for (const c of customChecks) {
      body.push(renderCustom(c));
      body.push('');
    }
  }

  const footer = `validator.save_expectation_suite(discard_failed_expectations=False)\n`;

  return header + body.join('\n') + footer;
}
