import { ConnectionConfig, CustomCheck, GenerateRequest, SelectedCheck } from '../types';

// ── configuration.yml comment block ────────────────────────────────────────

function configComment(cfg: ConnectionConfig | undefined, schema: string): string[] {
  const type = cfg?.type ?? 'postgres';
  const pkg  = sodaPackage(type);
  const yml  = configYml(cfg, schema);

  return [
    `# Soda Core — checks file`,
    `# Generated by DQ Test Builder`,
    `#`,
    `# 1. Install:  pip install ${pkg}`,
    `#`,
    `# 2. Save the following as configuration.yml`,
    `#    (replace the password placeholder with the real value or use env substitution):`,
    `#`,
    ...yml.map(l => `#   ${l}`),
    `#`,
    `# 3. Run:`,
    `#      soda scan -d ${schema} -c configuration.yml <this_file>.yml`,
    ``,
  ];
}

function sodaPackage(type: ConnectionConfig['type']): string {
  switch (type) {
    case 'snowflake': return 'soda-core-snowflake';
    case 'bigquery':  return 'soda-core-bigquery';
    case 'redshift':  return 'soda-core-redshift';
    default:          return 'soda-core-postgres';
  }
}

function configYml(cfg: ConnectionConfig | undefined, schema: string): string[] {
  if (!cfg) return defaultPostgresYml(schema);

  switch (cfg.type) {
    case 'snowflake':
      return [
        `data_sources:`,
        `  ${schema}:`,
        `    type: snowflake`,
        `    username: ${cfg.user ?? 'YOUR_USER'}`,
        `    password: \${SNOWFLAKE_PASSWORD}`,
        `    account: ${cfg.account ?? 'YOUR_ACCOUNT'}`,
        `    database: ${cfg.database ?? 'YOUR_DATABASE'}`,
        `    schema: ${cfg.schema ?? schema}`,
        `    warehouse: ${cfg.warehouse ?? 'YOUR_WAREHOUSE'}`,
        `    role: ${cfg.role ?? 'YOUR_ROLE'}`,
      ];

    case 'bigquery': {
      const lines = [
        `data_sources:`,
        `  ${schema}:`,
        `    type: bigquery`,
        `    account: ${cfg.projectId ?? cfg.database ?? 'YOUR_PROJECT'}`,
        `    auth_scopes:`,
        `      - https://www.googleapis.com/auth/cloud-platform`,
        `    dataset: ${cfg.dataset ?? schema}`,
      ];
      if (cfg.keyFile) lines.push(`    service_account_key_file: ${cfg.keyFile}`);
      return lines;
    }

    case 'redshift':
      return [
        `data_sources:`,
        `  ${schema}:`,
        `    type: redshift`,
        `    connection:`,
        `      host: ${cfg.host ?? 'YOUR_HOST'}`,
        `      port: ${cfg.port ?? 5439}`,
        `      database: ${cfg.database ?? 'YOUR_DATABASE'}`,
        `    username: ${cfg.user ?? 'YOUR_USER'}`,
        `    password: \${REDSHIFT_PASSWORD}`,
        `    schema: ${cfg.schema ?? schema}`,
      ];

    default:
      return [
        `data_sources:`,
        `  ${schema}:`,
        `    type: postgres`,
        `    connection:`,
        `      host: ${cfg.host ?? 'YOUR_HOST'}`,
        `      port: ${cfg.port ?? 5432}`,
        `      database: ${cfg.database ?? 'YOUR_DATABASE'}`,
        `    username: ${cfg.user ?? 'YOUR_USER'}`,
        `    password: \${DB_PASSWORD}`,
        `    schema: ${cfg.schema ?? schema}`,
      ];
  }
}

function defaultPostgresYml(schema: string): string[] {
  return [
    `data_sources:`,
    `  ${schema}:`,
    `    type: postgres`,
    `    connection:`,
    `      host: YOUR_HOST`,
    `      port: 5432`,
    `      database: YOUR_DATABASE`,
    `    username: YOUR_USER`,
    `    password: \${DB_PASSWORD}`,
    `    schema: ${schema}`,
  ];
}

// ── Per-check rendering ─────────────────────────────────────────────────────

function renderCheck(c: SelectedCheck): string {
  const p = c.params;
  const col = c.columnName;

  switch (c.checkId) {
    case 'missing_count':      return `  - missing_count(${col}) = 0`;
    case 'duplicate_count':    return `  - duplicate_count(${col}) = 0`;
    case 'missing_percent':    return `  - missing_percent(${col}) < ${p['threshold']}`;
    case 'duplicate_percent':  return `  - duplicate_percent(${col}) < ${p['threshold']}`;
    case 'valid_values': {
      const vals = p['values'].split(',').map(v => `'${v.trim()}'`).join(', ');
      return `  - invalid_count(${col}) = 0:\n      valid values: [${vals}]`;
    }
    case 'invalid_count': {
      const vals = p['values'].split(',').map(v => `'${v.trim()}'`).join(', ');
      return `  - invalid_count(${col}) = 0:\n      valid values: [${vals}]`;
    }
    case 'min_gte':         return `  - min(${col}) >= ${p['value']}`;
    case 'max_lte':         return `  - max(${col}) <= ${p['value']}`;
    case 'avg_between':     return `  - avg(${col}) between ${p['min']} and ${p['max']}`;
    case 'sum_between':     return `  - sum(${col}) between ${p['min']} and ${p['max']}`;
    case 'stddev_between':  return `  - stddev(${col}) between ${p['min']} and ${p['max']}`;
    case 'percentile':      return `  - percentile(${col}, ${p['pct']}) between ${p['min']} and ${p['max']}`;
    case 'min_length':      return `  - min_length(${col}) >= ${p['value']}`;
    case 'max_length':      return `  - max_length(${col}) <= ${p['value']}`;
    case 'avg_length':      return `  - avg_length(${col}) between ${p['min']} and ${p['max']}`;
    case 'freshness':       return `  - freshness(${col}) < ${p['duration']}`;
    case 'date_min':        return `  - min(${col}) >= '${p['value']}'`;
    case 'date_max':        return `  - max(${col}) <= '${p['value']}'`;
    default:                return `  # unknown check: ${c.checkId}`;
  }
}

function renderCustom(c: CustomCheck): string {
  return [
    `  - failed rows:`,
    `      name: ${c.name}`,
    `      fail condition: ${c.expression}`,
  ].join('\n');
}

// ── Main generator ──────────────────────────────────────────────────────────

export function generateSoda(req: GenerateRequest): string {
  const { table, checks, customChecks, connectionConfig } = req;
  const tableFqn = `${table.schema}.${table.table}`;

  const lines: string[] = [
    ...configComment(connectionConfig, table.schema),
    `checks for ${tableFqn}:`,
  ];

  const byColumn = new Map<string, SelectedCheck[]>();
  for (const c of checks) {
    if (!byColumn.has(c.columnName)) byColumn.set(c.columnName, []);
    byColumn.get(c.columnName)!.push(c);
  }

  for (const [col, colChecks] of byColumn) {
    lines.push(`  # ${col}`);
    for (const c of colChecks) lines.push(renderCheck(c));
  }

  if (customChecks.length > 0) {
    lines.push('  # custom checks');
    for (const c of customChecks) lines.push(renderCustom(c));
  }

  return lines.join('\n') + '\n';
}
