import { ConnectionConfig, CustomCheck, GenerateRequest, SelectedCheck } from '../types';

// ── Install + configuration.yml hints per DB type ───────────────────────────

function header(type: ConnectionConfig['type'] | undefined, schema: string): string {
  const pkg = sodaPackage(type);
  const cfgBlock = configBlock(type, schema);
  return [
    `# Soda Core — checks file`,
    `# Generated by DQ Test Builder`,
    `#`,
    `# Install:`,
    `#   pip install ${pkg}`,
    `#`,
    `# Create a configuration.yml with your data source credentials:`,
    ...cfgBlock.map(l => `#${l ? '   ' + l : ''}`),
    `#`,
    `# Run:`,
    `#   soda scan -d ${schema} -c configuration.yml <this_file>.yml`,
    ``,
  ].join('\n');
}

function sodaPackage(type: ConnectionConfig['type'] | undefined): string {
  switch (type) {
    case 'snowflake': return 'soda-core-snowflake';
    case 'bigquery':  return 'soda-core-bigquery';
    case 'redshift':  return 'soda-core-redshift';
    default:          return 'soda-core-postgres';
  }
}

function configBlock(type: ConnectionConfig['type'] | undefined, schema: string): string[] {
  switch (type) {
    case 'snowflake':
      return [
        `data_sources:`,
        `  ${schema}:`,
        `    type: snowflake`,
        `    username: YOUR_USER`,
        `    password: YOUR_PASSWORD`,
        `    account: YOUR_ACCOUNT`,
        `    database: YOUR_DATABASE`,
        `    schema: ${schema}`,
        `    warehouse: YOUR_WAREHOUSE`,
        `    role: YOUR_ROLE`,
      ];
    case 'bigquery':
      return [
        `data_sources:`,
        `  ${schema}:`,
        `    type: bigquery`,
        `    account: YOUR_PROJECT`,
        `    auth_scopes:`,
        `      - https://www.googleapis.com/auth/cloud-platform`,
        `    dataset: ${schema}`,
      ];
    case 'redshift':
      return [
        `data_sources:`,
        `  ${schema}:`,
        `    type: redshift`,
        `    connection:`,
        `      host: YOUR_HOST`,
        `      port: 5439`,
        `      database: YOUR_DATABASE`,
        `    username: YOUR_USER`,
        `    password: YOUR_PASSWORD`,
        `    schema: ${schema}`,
      ];
    default:
      return [
        `data_sources:`,
        `  ${schema}:`,
        `    type: postgres`,
        `    connection:`,
        `      host: YOUR_HOST`,
        `      port: 5432`,
        `      database: YOUR_DATABASE`,
        `    username: YOUR_USER`,
        `    password: YOUR_PASSWORD`,
        `    schema: ${schema}`,
      ];
  }
}

// ── Per-check rendering ─────────────────────────────────────────────────────

function renderCheck(c: SelectedCheck): string {
  const p = c.params;
  const col = c.columnName;

  switch (c.checkId) {
    case 'missing_count':      return `  - missing_count(${col}) = 0`;
    case 'duplicate_count':    return `  - duplicate_count(${col}) = 0`;
    case 'missing_percent':    return `  - missing_percent(${col}) < ${p['threshold']}`;
    case 'duplicate_percent':  return `  - duplicate_percent(${col}) < ${p['threshold']}`;
    case 'valid_values': {
      const vals = p['values'].split(',').map(v => `'${v.trim()}'`).join(', ');
      return `  - invalid_count(${col}) = 0:\n      valid values: [${vals}]`;
    }
    case 'invalid_count': {
      const vals = p['values'].split(',').map(v => `'${v.trim()}'`).join(', ');
      return `  - invalid_count(${col}) = 0:\n      valid values: [${vals}]`;
    }
    case 'min_gte':         return `  - min(${col}) >= ${p['value']}`;
    case 'max_lte':         return `  - max(${col}) <= ${p['value']}`;
    case 'avg_between':     return `  - avg(${col}) between ${p['min']} and ${p['max']}`;
    case 'sum_between':     return `  - sum(${col}) between ${p['min']} and ${p['max']}`;
    case 'stddev_between':  return `  - stddev(${col}) between ${p['min']} and ${p['max']}`;
    case 'percentile':      return `  - percentile(${col}, ${p['pct']}) between ${p['min']} and ${p['max']}`;
    case 'min_length':      return `  - min_length(${col}) >= ${p['value']}`;
    case 'max_length':      return `  - max_length(${col}) <= ${p['value']}`;
    case 'avg_length':      return `  - avg_length(${col}) between ${p['min']} and ${p['max']}`;
    case 'freshness':       return `  - freshness(${col}) < ${p['duration']}`;
    case 'date_min':        return `  - min(${col}) >= '${p['value']}'`;
    case 'date_max':        return `  - max(${col}) <= '${p['value']}'`;
    default:                return `  # unknown check: ${c.checkId}`;
  }
}

function renderCustom(c: CustomCheck): string {
  return [
    `  - failed rows:`,
    `      name: ${c.name}`,
    `      fail condition: ${c.expression}`,
  ].join('\n');
}

// ── Main generator ──────────────────────────────────────────────────────────

export function generateSoda(req: GenerateRequest): string {
  const { table, checks, customChecks, connectionType } = req;
  const tableFqn = `${table.schema}.${table.table}`;

  const lines: string[] = [
    header(connectionType, table.schema),
    `checks for ${tableFqn}:`,
  ];

  const byColumn = new Map<string, SelectedCheck[]>();
  for (const c of checks) {
    if (!byColumn.has(c.columnName)) byColumn.set(c.columnName, []);
    byColumn.get(c.columnName)!.push(c);
  }

  for (const [col, colChecks] of byColumn) {
    lines.push(`  # ${col}`);
    for (const c of colChecks) lines.push(renderCheck(c));
  }

  if (customChecks.length > 0) {
    lines.push('  # custom checks');
    for (const c of customChecks) lines.push(renderCustom(c));
  }

  return lines.join('\n') + '\n';
}
